#!/usr/bin/env bash

################################################################################
# Check for -h flag and provide instructions accordingly.                      #
################################################################################
if [ "$1" == "-h" ]; then
  echo Usage: $`basename $0` \<conversation-sid\>
  echo Lists the participants of the conversation for the provided conversation-sid.
  echo A conversation-sid is always of the form CHXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.
  exit 0
fi

################################################################################
# Variables                                                                    #
################################################################################
conversation_sid=${1?Error: Please provide a conversation-sid.}


################################################################################
# Main Programm                                                                #
################################################################################

twilio api:conversations:v1:conversations:participants:list \
    --conversation-sid $conversation_sid
